print('Quel animal a le plus grand nombre de dents ?')
input()
print('La petite souris !')
print()
print('Qu\'est qui est vert, qui monte et qui descend ?')
input()
print('Un petit pois dans un ascenseur !')
print()
print('Toc toc.')
input()
print("Qui est là ?")
input()

# Le paramètre clavier
print('Le chat qui interromptt MIA' , end='')
print('-OU !')